# Generated by Django 4.1.1 on 2022-10-05 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formularz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nr_Pracownika', models.DecimalField(decimal_places=0, max_digits=5)),
                ('Nr_Zlecenia', models.CharField(max_length=15)),
                ('Czas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Data', models.DateField(verbose_name=datetime.datetime(2022, 10, 10, 0, 0))),
            ],
        ),
    ]
