# Generated by Django 4.1.1 on 2022-10-19 05:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20, null=True)),
                ('name_book', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'Bubel',
            },
        ),
        migrations.CreateModel(
            name='Kod_Zlecenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nazwa_kodu', models.CharField(max_length=30, null=b'I01\n')),
                ('Numer_kodu', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Operacja',
                'verbose_name_plural': 'Operacje',
            },
        ),
        migrations.CreateModel(
            name='Lista_Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imie', models.CharField(max_length=50)),
                ('Nazwisko', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50, null=b'I01\n')),
            ],
            options={
                'verbose_name': 'Lista Email',
                'verbose_name_plural': 'Lista Email',
            },
        ),
        migrations.CreateModel(
            name='Nazwa_Wydzialu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nazwa_W', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Wydział',
                'verbose_name_plural': 'Wydziały',
            },
        ),
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nr_Pracownika', models.DecimalField(decimal_places=0, max_digits=5)),
                ('Imie', models.CharField(max_length=50)),
                ('Nazwisko', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Pracownik',
                'verbose_name_plural': 'Pracownicy',
            },
        ),
        migrations.CreateModel(
            name='Zabawa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oszaleje', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Zlecenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nr_Zlecenia', models.CharField(max_length=15)),
                ('Nazwa_Projektu', models.CharField(max_length=15, null=b'I01\n')),
            ],
            options={
                'verbose_name': 'Zlecenie',
                'verbose_name_plural': 'Zlecenia',
            },
        ),
        migrations.CreateModel(
            name='Formularz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Czas', models.DecimalField(decimal_places=2, max_digits=10, null=b'I01\n')),
                ('Data', models.DateField(null=b'I01\n', verbose_name=datetime.datetime(2022, 10, 10, 0, 0))),
                ('Kod_Zlecenia', models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to='Rejestracja.kod_zlecenia')),
                ('Nr_Zlecenia', models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to='Rejestracja.zlecenie')),
                ('Pracownik', models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to='Rejestracja.pracownik')),
            ],
            options={
                'verbose_name': 'Formulerz',
                'verbose_name_plural': 'Formularze',
                'db_table': 'Book',
            },
        ),
    ]
