# Generated by Django 4.1.1 on 2022-10-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rejestracja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kod_Zlecenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kod', models.DecimalField(decimal_places=0, max_digits=3)),
                ('Nazwa', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Nazwa_Wydzialu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nazwa_W', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nr_Pracownika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nr_Pracownika', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Zlecenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nr_Zlecenia', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='formularz',
            name='Nr_Pracownika',
        ),
        migrations.RemoveField(
            model_name='formularz',
            name='Nr_Zlecenia',
        ),
    ]
