# Generated by Django 4.1.1 on 2022-10-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rejestracja', '0002_kod_zlecenia_nazwa_wydzialu_nr_pracownika_zlecenie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nr_Pracownika', models.DecimalField(decimal_places=0, max_digits=5)),
                ('Imie', models.CharField(max_length=50)),
                ('Nazwisko', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Nr_Pracownika',
        ),
        migrations.AddField(
            model_name='zlecenie',
            name='Nazwa_Projektu',
            field=models.CharField(max_length=15, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
