# Generated by Django 4.1.1 on 2022-10-20 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rejestracja', '0002_delete_book_delete_zabawa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formularz',
            options={'verbose_name': 'Formulaz', 'verbose_name_plural': 'Formularze'},
        ),
    ]
