# Generated by Django 4.1.1 on 2022-10-24 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rejestracja', '0003_alter_formularz_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Formularz',
            new_name='Rejestracja_Lakiernia',
        ),
    ]
