# Generated by Django 4.1.1 on 2022-10-05 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rejestracja', '0003_pracownik_delete_nr_pracownika_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formularz',
            options={'verbose_name': 'Formulerz', 'verbose_name_plural': 'Formularze'},
        ),
        migrations.AlterModelOptions(
            name='kod_zlecenia',
            options={'verbose_name': 'Operacja', 'verbose_name_plural': 'Operacje'},
        ),
        migrations.AlterModelOptions(
            name='nazwa_wydzialu',
            options={'verbose_name': 'Wydział', 'verbose_name_plural': 'Wydziały'},
        ),
        migrations.AlterModelOptions(
            name='pracownik',
            options={'verbose_name': 'Pracownik', 'verbose_name_plural': 'Pracownicy'},
        ),
        migrations.AlterModelOptions(
            name='zlecenie',
            options={'verbose_name': 'Zlecenie', 'verbose_name_plural': 'Zlecenia'},
        ),
    ]
