# Generated by Django 4.1.1 on 2022-10-24 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rejestracja', '0004_rename_formularz_rejestracja_lakiernia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rejestracja_lakiernia',
            options={'verbose_name': 'Rejestracja Czasu Lakiernia', 'verbose_name_plural': 'Rejestracja Czasu Lakiernia'},
        ),
    ]
