# Generated by Django 4.1.1 on 2022-10-05 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rejestracja', '0004_alter_formularz_options_alter_kod_zlecenia_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kod_zlecenia',
            old_name='Nazwa',
            new_name='Nazwa_kodu',
        ),
    ]
