# Generated by Django 4.1.1 on 2022-10-24 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rejestracja', '0005_alter_rejestracja_lakiernia_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kod_Zlecenia',
            new_name='Kod_Zlecenia_Lakiernia',
        ),
        migrations.RenameModel(
            old_name='Pracownik',
            new_name='Pracownik_Lakiernia',
        ),
        migrations.RenameModel(
            old_name='Zlecenie',
            new_name='Zlecenie_Lakiernia',
        ),
    ]
