# Generated by Django 4.1.1 on 2022-10-06 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rejestracja', '0005_rename_nazwa_kod_zlecenia_nazwa_kodu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kod_zlecenia',
            old_name='Kod',
            new_name='Kod_zl',
        ),
    ]
