# Generated by Django 4.1.1 on 2022-10-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rejestracja', '0006_rename_kod_kod_zlecenia_kod_zl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kod_zlecenia',
            name='Kod_zl',
        ),
        migrations.AlterField(
            model_name='kod_zlecenia',
            name='Nazwa_kodu',
            field=models.CharField(max_length=30, null=b'I01\n'),
        ),
    ]
