# Generated by Django 4.1.1 on 2022-10-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rejestracja', '0007_remove_kod_zlecenia_kod_zl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kod_zlecenia',
            name='Numer_kodu',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
