# Generated by Django 4.1.1 on 2022-10-06 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rejestracja', '0008_kod_zlecenia_numer_kodu'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularz',
            name='Wydział',
            field=models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to='Rejestracja.nazwa_wydzialu'),
            preserve_default=b'I01\n',
        ),
    ]
