# Generated by Django 4.1.1 on 2022-10-06 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rejestracja', '0009_formularz_wydział'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularz',
            name='Czas',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='formularz',
            name='Data',
            field=models.DateField(null=b'I01\n', verbose_name=datetime.datetime(2022, 10, 10, 0, 0)),
        ),
    ]
