# Generated by Django 4.1.1 on 2022-10-06 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rejestracja', '0010_alter_formularz_czas_alter_formularz_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularz',
            name='Kod_Zlecenia',
            field=models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to='Rejestracja.kod_zlecenia'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='formularz',
            name='Nr_Zlecenia',
            field=models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to='Rejestracja.zlecenie'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='formularz',
            name='Pracownik',
            field=models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, to='Rejestracja.pracownik'),
            preserve_default=b'I01\n',
        ),
    ]
